### PR TITLE
fix "show elements pane" in chrome extension #109

### LINKED ISSUE #109: [New DevTools] Show in Elements Pane not working in Opera
Hi,

I’m using the new beta Chrome extension in Opera (v30). When I right-click on a node within the React DevTools, it shows the option "Show in Elements Pane", but clicking it doesn’t appear to do anything. The other options, such as "Show Source" work okay though.

### PR DESCRIPTION
**Pull request by jaredly**
and add more flowtypes such that similar errors would be automatically detected

fixes #109

### CODE REVIEW

File: shells/chrome/src/panel.js [hunk 1]
```diff
@@ -56,7 +59,7 @@ var config = {
     chrome.devtools.inspectedWindow.eval('window.__REACT_DEVTOOLS_GLOBAL_HOOK__.$0 = $0');
     bridge.send('checkSelection');
   },
-  selectElement(bridge, id) {
+  selectElement(id, bridge) {
```
Comment (jaredly) [inline shells/chrome/src/panel.js]: this is where the error was

**Comment by jaredly** [comment]
@frantic could you check this out?
