### PR TITLE
Fix #248, when an <option> contains raw strings

### LINKED ISSUE #248: Multiple <option> children causes TypeError: Cannot read property 'props' of undefined
When I open react-devtools, I see this:

screenshot 2015-10-07 12 14 45

After clicking the button, it fails with this error:

screenshot 2015-10-07 12 16 47

I tried closing the tab and opening everything again, but the problem persists.

My page uses React `0.14-rc1`. I tried react-devtools on another page that uses react `0.13` and it works fine (in spite of the warning about version).

### PR DESCRIPTION
**Pull request by jaredly**
[awkward that this was a bug for so long...]

The bug is easily replicable (see https://github.com/facebook/react-devtools/issues/248), and the problem is
that `element` is just a string in that case, such that there is no
`element._currentElement`.

Test Plan:
Go to a page with `<option>some text {1}</option>`, see that devtools doesn't
break.

### CODE REVIEW

**Comment by spicyj** [comment]
What do the devtools show after this?

**Comment by jaredly** [comment]
Good call. fixed so that devtools actually shows something useful. If a raw value is entered, it is coerced to a string (as the web does)
image

File: backend/getData.js [hunk 1]
```diff
@@ -27,7 +27,11 @@ function getData(element: Object): DataType {
   var text = null;
   var publicInstance = null;
   var nodeType = 'Native';
-  if (element._currentElement === null || element._currentElement === false) {
+  // Sometimes element is just a string or number
+  if (typeof element !== "object") {
```
Comment (spicyj) [inline backend/getData.js]: I thought `element._currentElement` was a string/number. Am I misunderstanding here?

Comment (jaredly) [inline backend/getData.js]: It is... most of the time. Just not when you've got a string element of an `<option/>`, which is what has been causing #248. In that case, and only in that case, `element._renderedChildren` is a list of raw strings/numbers, b/c it's not allowed to put a `<span>` inside of an `<option>`. In every other case, if there are multiple children, then `element._renderedChildren` is a list of more elements.

Comment (spicyj) [inline backend/getData.js]: `_renderedChildren` should be null: http://react.jsbin.com/dikerovequ/edit?js,output.

Comment (jaredly) [inline backend/getData.js]: oh you're right I misspoke. If `_renderedChildren` is null, then we iterate through the `props.children`, which contains plain values. I've updated the comment to be more accurate

**Comment by jaredly** [comment]
@spicyj bump?

**Comment by AaronHarris** [comment]
This is also a blocking issue for me. Is there any reason @spicyj this cannot be merged?

**Comment by nicolanicola** [comment]
can this be merged please?  Its blocking me

**Comment by spicyj** [comment]
All the duck typing here really freaks me out but I guess this is okay.
