### PR TITLE
Fix: Better display for string contexts

### LINKED ISSUE #1212: Better display for string contexts
When using `<SomeContext.Provider value="string">` and consuming that with the new `contextType` from React 16.6.0, the devtools displays the context value like an array:

```
0: "s"
1: "t"
2: "r"
3: "i"
4: "n"
5: "g"
```

It would be nicer if it was displayed something like this:

```
"string"
```

Test page:

```html
<!doctype html>
<meta charset="utf-8">
<title>React Context test</title>
<div id="container"></div>
<script src="https://unpkg.com/react@16.6.0/umd/react.development.js"></script>
<script src="https://unpkg.com/react-dom@16.6.0/umd/react-dom.development.js"></script>

<script>
  const LanguageContext = React.createContext();

  class Test extends React.Component {
    render() {
      return React.createElement("p", {}, `Language: ${this.context}`);
    }
  }

  Test.contextType = LanguageContext;

  ReactDOM.render(
    React.createElement(
      LanguageContext.Provider,
      { value: "en-us" },
      React.createElement(Test),
    ),
    container
  );
</script>
```

Screenshot:

screenshot from 2018-11-01 15-23-03

### PR DESCRIPTION
**Pull request by yifei-fu**
Closes #1212.
DataView now accepts any type of data (not just objects) and displays primitive values properly.
image

### CODE REVIEW

File: frontend/DataView/DataView.js [hunk 1]
```diff
@@ -74,9 +74,20 @@ class DataView extends React.Component<DataViewProps> {
       return <div style={missingStyle(theme)}>null</div>;
     }
 
+    const dataType = typeof data;
+    var isPrimitive = dataType === 'number' || dataType === 'string' || dataType === 'boolean';
```
[the remark this answers is not in the document]
Comment (yifei-fu) [reply frontend/DataView/DataView.js]: Found that as well. I'm pretty sure it's unrelated to the changes because numbers are not displayed when testing on the master branch. I'll probably open an issue for that.

File: frontend/DataView/DataView.js [hunk 2]
```diff
@@ -74,9 +74,20 @@ class DataView extends React.Component<DataViewProps> {
...
     }
 
+    const dataType = typeof data;
+    var isSingleValue = dataType === 'number' || dataType === 'string' || dataType === 'boolean';
     var isArray = Array.isArray(data);
     var elements = [];
-    if (isArray) {
+    if (isSingleValue) {
+      elements.push(<DataItem
+          name={''}
```
Comment (bvaughn) [inline frontend/DataView/DataView.js]: Even though this is a single value, since we're adding it to an array– it needs a `key`.

File: frontend/DataView/DataView.js [hunk 3]
```diff
@@ -74,9 +74,20 @@ class DataView extends React.Component<DataViewProps> {
...
+          hideName={true}
+          path={this.props.path}
+          inspect={this.props.inspect}
+          showMenu={this.props.showMenu}
+          readOnly={this.props.readOnly}
```
Comment (bvaughn) [inline frontend/DataView/DataView.js]: This case should be read-only, because we can't actually edit the context value without crawling upwards and mutating the ancestor context. (We _can_ override the value on the instance, but React will reset it when we call `forceUpdate` so the change won't actually stick.)

File: frontend/DataView/DataView.js [hunk 4]
```diff
@@ -74,9 +74,20 @@ class DataView extends React.Component<DataViewProps> {
       return <div style={missingStyle(theme)}>null</div>;
     }
 
+    const dataType = typeof data;
+    var isSingleValue = dataType === 'number' || dataType === 'string' || dataType === 'boolean';
```
Comment (bvaughn) [inline frontend/DataView/DataView.js]: I kind of prefer "simple type" rather than "single value" but this is just a subject nit
